trigger:
  branches:
    include:
      - main

variables:
  imageName: 'nodejsdemoapp'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerInstaller@0

- task: Docker@2
  displayName: Build and Push Docker Image
  inputs:
    command: buildAndPush
    repository: $(imageName)
    dockerfile: '**/Dockerfile'
    containerRegistry: 'YourACRServiceConnection'
    tags: |
      $(Build.BuildId)

- task: AzureWebAppContainer@1
  displayName: Deploy to Azure Web App
  inputs:
    azureSubscription: 'YourAzureServiceConnection'
    appName: 'your-web-app-name'
    containers: 'youracr.azurecr.io/$(imageName):$(Build.BuildId)'
  